[package]
name = "rustboy-adapter-debugger-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Terminal debugger adapter for Rustboy."
license.workspace = true

[[bin]]
name = "rustboy-debugger"
path = "src/main.rs"

[dependencies]
rustboy-debugger = { path = "../rustboy-debugger" }
