[package]
name = "rustboy-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Command-line entry point for Rustboy."
license.workspace = true

[[bin]]
name = "rustboy"
path = "src/main.rs"

[dependencies]
rustboy-core = { path = "../rustboy-core" }
rustboy-application = { path = "../rustboy-application" }
rustboy-adapter-rom = { path = "../rustboy-adapter-rom" }
rustboy-adapter-sdl3 = { path = "../rustboy-adapter-sdl3" }
