[package]
name = "rustboy-adapter-sdl3"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "SDL3 input, video, and audio adapters for Rustboy."
license.workspace = true

[dependencies]
rustboy-application = { path = "../rustboy-application" }
rustboy-core = { path = "../rustboy-core" }
sdl3 = "0.20.0"
