[package]
name = "rustboy-core"
version.workspace = true
authors = ["Franz Hess <zylonenoger@gmail.com>"]
edition.workspace = true
rust-version.workspace = true
description = "Game Boy emulation core for Rustboy."
license.workspace = true
repository = "https://github.com/franzhess/rustboy"
keywords = ["game-boy", "emulator"]
categories = ["emulators"]

[dependencies]
